---

- name: Make sure tinc is installed or upgraded
  ansible.builtin.include_tasks:
    file: install.yml
  tags: [install, upgrade]
  when: "'members' in group_names"

- name: Remove tinc configuration from removed node
  ansible.builtin.include_tasks:
    file: remove.yml
  tags: [remove]
  when: "'removed' in group_names"

- name: Cleanup removed nodes information from cluster
  ansible.builtin.include_tasks:
    file: remove_key.yml
  tags: [remove]
  when: "'members' in group_names"


