---

- name: Remove lines in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ network_name }}.*"
    state: absent

- name: Remove nets.conf entry
  lineinfile:
    dest: "{{ tinc_root_folder }}/nets.boot"
    regexp: "{{ network_name }}"
    state: absent

- name: Rremove full tinc conf {{ network_name }} folder
  file:
    path: "{{ tinc_root_folder }}/{{ network_name }}"
    state: absent

- name: Rremove public key from tinc hosts
  file:
    path: "/etc/tinc/{{ network_name }}/hosts/{{ item }}"
    state: absent
  with_items:
    - "{{ groups['members'] }}"

- name: Stop service
  systemd:
    name: "tinc@{{ network_name }}"
    enabled: no
